version: '3'
services:
  golang:
    container_name: db-api
    build: .
    networks:
      itaic-net:
        ipv4_address: 176.24.0.3
    ports:
      - '8000:8000'
  golang:
    container_name: cache-api
    image: itaic-cache
    networks:
      - itaic-net
    ports:
      - '5000:5000'
  rabbitmq:
    container_name: queue,
    image: rabbitmq
    networks:
      itaic-net:
        ipv4_address: 176.24.0.9
    ports:
      - '5672:5672'
  redis-server:
    container_name: cache
    image: redis
    networks:
      itaic-net:
        ipv4_address: 176.24.0.1

networks:
  itaic-net:
    driver: bridge
    ipam:
      config:
        - subnet: 176.24.0.0/24
